### ISSUE TITLE
Improve triage yaml format

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/glvd#139]
Currently, adding triage data is done with this yaml format (with a few more optional fields)

```yaml
- cves:
    - CVE-2024-53141
  dists:
    - '1592.5'
  is_resolved: true
  description: |
    some description
```

This format works, but it might require adding multiple entries for multiple Garden Linux versions, for example in the case of CVE-2024-53141, Garden Linux 1592.4 is vulnerable, and in the upcoming 1592.5 it is going to be fixed.

With the current implementation, this could be expressed with two entries, like here:

```yaml
- cves:
    - CVE-2024-53141
  dists:
    - '1592.4'
  is_resolved: false
  description: |
    this is a real vulnerability and you should do x and y to mitigate it
- cves:
    - CVE-2024-53141
  dists:
    - '1592.5'
  is_resolved: true
  description: |
    this vulnerability is fixed by upgrading linux to version 6.6.71 which fixed it
```

Adding the entry for the vulnerable version makes sense because additional context can be provided, for example with the description that might give the users hints on how to mitigate the issue.

Adding the entry for the not vulnerable future release makes sense because it provides information on resolved vulnerabilities.

The suggestion in this issue is to change the format of the yaml files slightly to allow merging both entries into one like this:

```yaml
- cves:
    - CVE-2024-53141
  dists:
    affected:
    - '1592.4'
    resolved:
    - '1592.5'
  description: |
    this is a real vulnerability and you should do x and y to mitigate it
    this vulnerability is fixed in 1592.5 by upgrading linux to version 6.6.71 which fixed it
```

The boolean `is_resolved` property is removed, and instead the `dists` property has two new entries, one with a list of affected (i.e. not resolved) dists, and one with resolved.

The difference here is also that the same description field is used in both dists, which seems sensible to me, but we might also have 2 serape description fields. I'm trying to keep the format simple, so I don't want to allow all possible variations, and I think one description field for both cases is fine.
